<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: revision.proto

namespace GPBMetadata;

class Revision
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa7020a0e7265766973696f6e2e70726f746f12175265766973696f6e43" .
            "6c69656e74496e7465726661636522440a0f5265766973696f6e52657175" .
            "65737412120a0a6a6f75726e616c5f6964180120012803120c0a046e616d" .
            "65180220012809120f0a0772656d61726b7318032001280922430a105265" .
            "766973696f6e526573706f6e7365120c0a04666c6167180120012809120f" .
            "0a076d65737361676518022001280912100a085265766973696f6e180320" .
            "01280932690a085265766973696f6e125d0a0643726561746512282e5265" .
            "766973696f6e436c69656e74496e746572666163652e5265766973696f6e" .
            "526571756573741a292e5265766973696f6e436c69656e74496e74657266" .
            "6163652e5265766973696f6e526573706f6e7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

