<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: revision.proto

namespace RevisionClientInterface;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RevisionClientInterface.RevisionResponse</code>
 */
class RevisionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string flag = 1;</code>
     */
    private $flag = '';
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    private $message = '';
    /**
     * Generated from protobuf field <code>string Revision = 3;</code>
     */
    private $Revision = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $flag
     *     @type string $message
     *     @type string $Revision
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Revision::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string flag = 1;</code>
     * @return string
     */
    public function getFlag()
    {
        return $this->flag;
    }

    /**
     * Generated from protobuf field <code>string flag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFlag($var)
    {
        GPBUtil::checkString($var, True);
        $this->flag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Revision = 3;</code>
     * @return string
     */
    public function getRevision()
    {
        return $this->Revision;
    }

    /**
     * Generated from protobuf field <code>string Revision = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRevision($var)
    {
        GPBUtil::checkString($var, True);
        $this->Revision = $var;

        return $this;
    }

}

