<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: revision.proto

namespace RevisionClientInterface;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RevisionClientInterface.RevisionRequest</code>
 */
class RevisionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 journal_id = 1;</code>
     */
    private $journal_id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string remarks = 3;</code>
     */
    private $remarks = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $journal_id
     *     @type string $name
     *     @type string $remarks
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Revision::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 journal_id = 1;</code>
     * @return int|string
     */
    public function getJournalId()
    {
        return $this->journal_id;
    }

    /**
     * Generated from protobuf field <code>int64 journal_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setJournalId($var)
    {
        GPBUtil::checkInt64($var);
        $this->journal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string remarks = 3;</code>
     * @return string
     */
    public function getRemarks()
    {
        return $this->remarks;
    }

    /**
     * Generated from protobuf field <code>string remarks = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRemarks($var)
    {
        GPBUtil::checkString($var, True);
        $this->remarks = $var;

        return $this;
    }

}

