<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: journal.proto

namespace JournalClientInterface;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>JournalClientInterface.JournalResponse</code>
 */
class JournalResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string flag = 1;</code>
     */
    private $flag = '';
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    private $message = '';
    /**
     * Generated from protobuf field <code>string Journal = 3;</code>
     */
    private $Journal = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $flag
     *     @type string $message
     *     @type string $Journal
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Journal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string flag = 1;</code>
     * @return string
     */
    public function getFlag()
    {
        return $this->flag;
    }

    /**
     * Generated from protobuf field <code>string flag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFlag($var)
    {
        GPBUtil::checkString($var, True);
        $this->flag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Journal = 3;</code>
     * @return string
     */
    public function getJournal()
    {
        return $this->Journal;
    }

    /**
     * Generated from protobuf field <code>string Journal = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setJournal($var)
    {
        GPBUtil::checkString($var, True);
        $this->Journal = $var;

        return $this;
    }

}

