<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: journal.proto

namespace JournalClientInterface;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>JournalClientInterface.JournalCreateRequest</code>
 */
class JournalCreateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>string title = 2;</code>
     */
    private $title = '';
    /**
     * Generated from protobuf field <code>string overview = 3;</code>
     */
    private $overview = '';
    /**
     * Generated from protobuf field <code>uint64 journal_category_id = 4;</code>
     */
    private $journal_category_id = 0;
    /**
     * Generated from protobuf field <code>uint64 user_id = 5;</code>
     */
    private $user_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $title
     *     @type string $overview
     *     @type int|string $journal_category_id
     *     @type int|string $user_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Journal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string overview = 3;</code>
     * @return string
     */
    public function getOverview()
    {
        return $this->overview;
    }

    /**
     * Generated from protobuf field <code>string overview = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOverview($var)
    {
        GPBUtil::checkString($var, True);
        $this->overview = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 journal_category_id = 4;</code>
     * @return int|string
     */
    public function getJournalCategoryId()
    {
        return $this->journal_category_id;
    }

    /**
     * Generated from protobuf field <code>uint64 journal_category_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setJournalCategoryId($var)
    {
        GPBUtil::checkUint64($var);
        $this->journal_category_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 5;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_id = $var;

        return $this;
    }

}

